services:
  - type: web
    name: lstm-plag-detector
    env: python
    pythonVersion: "3.10"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1